### ISSUE TITLE
Support and flatten .geojson files

### ISSUE THREAD

**Issue by RandomFractals** [githubocto/flat-viewer#12]
This would make many GIS devs and experts very happy.

See this data wrangling ticket for more context info: https://github.com/RandomFractals/vscode-leaflet/issues/9

and sensible defaults and conventions that could be used for converting geo data to flat data files: https://github.com/keplergl/kepler.gl/blob/master/docs/user-guides/b-kepler-gl-workflow/a-add-data-to-the-map.md#supported-file-formats

**Comment by RandomFractals** [comment]
@LoneRifle: any update on this geojson data view support merge?

I just tried it, but it looks like it's not available yet :disappointed: 

![image](https://user-images.githubusercontent.com/656833/122962359-f6684000-d34a-11eb-8520-b72f7eadd5fd.png)

see: https://flatgithub.com/RandomFractals/geo-data-viewer?filename=data%2Ftopojson%2Fusa-albers-counties.topo.geojson&sha=d85e8857fef32bfb96d3d1eeebf1fc04669dd052

looks nice in the default github file view tho: https://github.com/RandomFractals/geo-data-viewer/blob/master/data/topojson/usa-albers-counties.topo.geojson

**Comment by LoneRifle** [comment]
I don't work for GitHub, so you should direct your queries to the others on this repo.

**Comment by RandomFractals** [comment]
oh, that was quite a contribution. 

@Wattenberger can you please review that PR and merge?

Thanks!

**Comment by LoneRifle** [comment]
githubocto/flat-ui#11 was merged into release 0.9.4 of the corresponding npm package; CSV downloads of features in FeatureCollection objects should hence have properly formatted geometry JSON, in-line with kepler.gl guidelines.

**Comment by RandomFractals** [comment]
ok. I'll check. Thanks for your update.

**Comment by LoneRifle** [comment]
> nope. same result as above. try it: https://flatgithub.com/RandomFractals/geo-data-viewer?filename=data%2Ftopojson%2Fusa-albers-counties.topo.geojson&sha=d85e8857fef32bfb96d3d1eeebf1fc04669dd052

That's due to the extension of the files concerned; flat-viewer avoids .geojson.

**Comment by RandomFractals** [comment]
idk. If this loads a leaflet map: https://github.com/RandomFractals/geo-data-viewer/blob/master/data/topojson/usa-albers-counties.topo.geojson

I would expect `.geojson` file to load in `flat-viewer` in a data grid.

That's why I opened this request.

**Comment by Wattenberger** [comment]
Flat Viewer now handles geojson & topojson files, as well as spreading the nested properties into columns

**Comment by RandomFractals** [comment]
Thank you!
