### ISSUE TITLE
Datetime columns do not display correctly on mobile

### ISSUE THREAD

**Issue by nsgrantham** [githubocto/flat-viewer#16]
Fantastic work on Flat, GitHub OCTO! 🐙

I've used Flat Data to grab the 7-day asteroid forecast from NASA's Near Earth Object API.

Opening Flat Viewer on `nasa-asteroids-postprocessed.csv` on desktop, everything looks great: [https://flatgithub.com/nsgrantham/nasa-asteroids](https://flatgithub.com/nsgrantham/nasa-asteroids)

However, when opened on mobile (iOS 14.4.2 using Safari and Chrome), there appears to be a problem with the datetime columns `close_approach_datetime` and `orbit_determination_datetime`.

![flat-viewer-datetime-mobile](https://user-images.githubusercontent.com/4433521/119240739-a6f1e280-bb06-11eb-814e-41d2ab55de5e.jpg)

These columns are of the form `yyyy-MM-dd HH:mm` and `yyyy-MM-dd HH:mm:ss` respectively.

There is no problem with the regular date columns of the form `yyyy-MM-dd`.

**Comment by Wattenberger** [comment]
should be all set - thanks for the flag @nsgrantham!
