### ISSUE TITLE
Unique file names for downloads

### ISSUE THREAD

**Issue by blink-twice** [githubocto/flat-viewer#19]
Files downloaded from Flat Viewer have the name **flat-ui__data \<timestamp\>.extension**. . Would it be possible to use **flat-ui_\<timestamp\>_\<filename\>** or similar naming schemes to make it easy to identify them?

**Comment by RandomFractals** [comment]
also, why use both - and _ in a file name. go with dashes if you ask me.

maybe it should be just `<filename>-<iso-date-time>.<file-ext>`. 

I really dont-want to strip out the `flat-ui` flie name prefix from those file name saves.

Thanks!

**Comment by Wattenberger** [comment]
👍 updated in 1491dc2d0b07f6718af44d264b5e084e28ac5548 & 5948ea90a3d0884ef714fd623fd19be102964039

**Comment by RandomFractals** [comment]
how is this fixed? I see you still left your prefix there, just renamed it: ` const downloadFilename = `flat-data--${date}-${filename}`;`
