### ISSUE TITLE
feat: list repos tagged with `flat-data` if only org is specified

### ISSUE THREAD

**Issue by LoneRifle** [githubocto/flat-viewer#24]
For non-technical users, Flat Viewer as hosted on [flatgithub.com](https://flatgithub.com) has been effective for exploring tabular data hosted on GitHub repositories. A team could create a GitHub organization containing Flat Data repositories, each one set with the corresponding flatgithub.com URL, and non-technical users can then be directed to explore these repositories on `github.com/<org-name>`.

However, given how GitHub's UI is tailored mostly for developers, non-technical users may be unfamiliar (and possibly unwilling to be familiar) with reading through a list of repositories on a GitHub org page, and would hence be intimidated from exploring further.

To help such users, Flat Viewer could implement the listing of repositories that contain Flat Data (identified by eg being tagged with `flat-data`) within a given GitHub organization. Users can then look at a GitHub org's `flat-data` repos, through an interface specifically for exploring Flat Data, via a URL like `flatgithub.com/<org-name>`.

**Comment by mattrothenberg** [comment]
Wonderful suggestion!

Take a look and let us know if that's what you had in mind.

**Comment by LoneRifle** [comment]
This works really well! Similarity to GitHub's layout on the equivalent page is a nice plus. Thanks for building this out!

**Comment by RandomFractals** [comment]
good. maybe add a pic to this repo too and pull pics from repos tagged with `flat-data` ;) https://flatgithub.com/RandomFractals
