### ISSUE TITLE
Feature request: Private repo support

### ISSUE THREAD

**Issue by declann** [githubocto/flat-viewer#33]
Hi!

Great tool!

I know it would require new auth plumbing but I think it would be even better if I the viewer could work for private repos!

**Comment by Wattenberger** [comment]
Thanks for the feedback! You can actually add a `token` in your local storage with a [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) with `repo` access to view private repos

**Comment by declann** [comment]
Excellent!
I looked at the code and found the token name should be `flat-viewer-pat`, now I can access my private repos (commits/filenames).
But I still get a problem viewing files, so I filed separate issue #35 
Thanks a lot for the response.

**Comment by Wattenberger** [comment]
ah, thank you for correcting me! I was thinking of another project, it is indeed `flat-viewer-pat` for the Flat viewer
