### ISSUE TITLE
UI: sticker/link back to flat-viewer github repo

### ISSUE THREAD

**Issue by declann** [githubocto/flat-viewer#34]
I think this is worth considering 😃 

UI/homepage leaves lots of space for a sticker, and repo gives a lot of helpful context about the tool which the UI/homepage doesn't (being nice and concise themselves)

**Comment by Wattenberger** [comment]
great idea to add more info! I added a link to the writeup, which walks through the background and links to all of the things
![image](https://user-images.githubusercontent.com/3506269/143929220-62bb98cf-89b4-47ce-aad8-2350d20df507.png)
