### ISSUE TITLE
404 error in private repo

### ISSUE THREAD

**Issue by declann** [githubocto/flat-viewer#35]
Hi!

I'm trying to use flat viewer on a private repo (via local storage token).
Flat viewer can access files/commits, but I get an error in the data viewer pane: "Oh no, we couldn't load x/y.csv for some reason".

A 404 is logged to console because looking up the pattern:
`https://raw.githubusercontent.com/${owner}/${name}/${sha}/${filename}`
gives a 404 for my private repo.

Not sure whats wrong - should there be a token included in the URL (for private repos) for instance? (github links to raw data in a private repo using `?token=...`)

**Comment by Wattenberger** [comment]
great catch - this should work now! We need to use the contents REST API endpoint instead of the raw url for private repos

**Comment by declann** [comment]
working great, thanks!
