### ISSUE TITLE
not recognizing number

### ISSUE THREAD

**Issue by fgregg** [githubocto/flat-viewer#36]
thanks for the great tool!

flatgithub.com is not recognizing a field that contains only integers and empty value as a number:

https://flatgithub.com/labordata/nlrb-voluntary-recognitions?filename=voluntary_recognitions.csv&sha=366cf624c4bc0f870e1aa41fcd6a3425214843e2

I've verified that there are no sneaky thousand separators or anything else.

The column in question is the "Number of employees" field

**Comment by Wattenberger** [comment]
ah thanks for flagging! We were being over-eager when checking for colors - fixed

**Comment by fgregg** [comment]
thanks!
