### ISSUE TITLE
numbers not sorting correctly

### ISSUE THREAD

**Issue by fgregg** [githubocto/flat-viewer#37]
Sorting by numbers seems to get confused if there are blank values as well.

https://flatgithub.com/labordata/nlrb-voluntary-recognitions?filename=voluntary_recognitions.csv&filters=&sha=d9d936a07f6d8084063e1321202bec3fb087a07f&sort=Number%20of%20Employees%2Cdesc&stickyColumnName=VR%20Case%20Number

![Screenshot 2022-01-31 at 14-36-25 labordata nlrb-voluntary-recognitions – Flat](https://user-images.githubusercontent.com/536941/151860706-5166dc9a-31fd-4578-9159-ea389bc562b5.png)

**Comment by Wattenberger** [comment]
great catch - fixed! thanks for flagging
