### ISSUE TITLE
New line character issue

### ISSUE THREAD

**Issue by anuveyatsu** [githubocto/flat-viewer#45]
It looks like we can't have `\r\n` as a new line character in CSV and should use `\n`.

Looking at data fetcher in this repo, I found https://github.com/githubocto/flat-viewer/blob/main/src/api/index.ts#L142 which parses CSV using https://github.com/githubocto/flat-viewer/blob/main/src/api/index.ts#L7

So it looks like that parser is here https://github.com/d3/d3-dsv/blob/main/src/dsv.js

**Comment by sagargg** [comment]
@anuveyatsu No it's the opposite, it's not generating the correct table for windows-style line ending `\r\n`.

**Comment by anuveyatsu** [comment]
OK looks like this issue is INVALID because we're implementing custom data fetcher and parser due to our requirements. So probably your fetcher works ok 😄 sorry for confusion!
