### ISSUE TITLE
Doesn't properly handle repos with . in URI

### ISSUE THREAD

**Issue by Smittyvb** [githubocto/flat-viewer#6]
Going to https://flatgithub.com/smittyvb/smitop.com gives a 404, while going to the main page and entering `Smittyvb` and `smitop.com` works as expected.

**Comment by mattrothenberg** [comment]
Thanks for reporting @Smittyvb, this should be fixed now by https://github.com/githubocto/flat-viewer/commit/0c87b92015e87e4c0330b02a1e7618f00257ee36
